---
title: "Example 01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Predicting cross-reactivity targets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

```{r, warning = FALSE}

library(crossdome)
library(dplyr)

background <- cross_universe(off_targets = 'ESDPIVAQY', allele = "HLA-A*01:01")
result <- cross_compose(query = 'EVDPIGHLY', object = background)

```

```{r}

str(result)

```

```{r}

result <- result %>%
  mutate(
    off_target = ifelse(subject == "ESDPIVAQY", "Yes", "No")
  )

```

```{r fig.height = 14, fig.width = 12, paged.print = TRUE}

result <- cross_expression_matrix(result, pvalue_threshold = 0.005)
cross_expression_heatmap(object = result)

```

```{r fig.height = 8, fig.width = 12, paged.print = TRUE}

#cross_prediction_plot(object = result)
#cross_xr_risk_plot(object = result)

```

```{r}

#result <- cross_substitution_matrix(result)
#cross_substitution_plot(object = result)

```


```{r}

#result_top <- result %>%
#   filter(pvalue <= 0.01)

if(FALSE) {
    cross_write(result_top, file = "/tmp/crossdome_top_results.tsv")
}

```
